#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;


namespace TeamThing.Model	
{
	public partial class EmailLog
	{
		private int _emailLogId;
		public virtual int EmailLogId 
		{ 
		    get
		    {
		        return this._emailLogId;
		    }
		    set
		    {
		        this._emailLogId = value;
		    }
		}
		
		private string _subject;
		public virtual string Subject 
		{ 
		    get
		    {
		        return this._subject;
		    }
		    set
		    {
		        this._subject = value;
		    }
		}
		
		private string _toAddress;
		public virtual string ToAddress 
		{ 
		    get
		    {
		        return this._toAddress;
		    }
		    set
		    {
		        this._toAddress = value;
		    }
		}
		
		private DateTime _sendDate;
		public virtual DateTime SendDate 
		{ 
		    get
		    {
		        return this._sendDate;
		    }
		    set
		    {
		        this._sendDate = value;
		    }
		}
		
		private Team _team;
		public virtual Team Team 
		{ 
		    get
		    {
		        return this._team;
		    }
		    set
		    {
		        this._team = value;
		    }
		}
		
		private TeamMember _teamMember;
		public virtual TeamMember TeamMember 
		{ 
		    get
		    {
		        return this._teamMember;
		    }
		    set
		    {
		        this._teamMember = value;
		    }
		}
		
		private EmailType _emailType;
		public virtual EmailType EmailType 
		{ 
		    get
		    {
		        return this._emailType;
		    }
		    set
		    {
		        this._emailType = value;
		    }
		}
		
	}
}
