#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;


namespace TeamThing.Model	
{
	public interface IThing
	{
		int ThingId 
		{ 
			get;
			set;
		}
		string Description 
		{ 
			get;
			set;
		}
		TeamMember TeamMember 
		{ 
			get;
			set;
		}
		DateTime DateCreated 
		{ 
			get;
			set;
		}
		ThingSource ThingSource 
		{ 
			get;
			set;
		}
	}
}
