#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;


namespace TeamThing.Model	
{
	public partial class Team
	{
		private int _teamId;
		public virtual int TeamId 
		{ 
		    get
		    {
		        return this._teamId;
		    }
		    set
		    {
		        this._teamId = value;
		    }
		}
		
		private IList<TeamMember> _teamMembers;
		public virtual IList<TeamMember> TeamMembers 
		{ 
		    get
		    {
		        return this._teamMembers;
		    }
		    set
		    {
		        this._teamMembers = value;
		    }
		}
		
		private string _teamName;
		public virtual string TeamName 
		{ 
		    get
		    {
		        return this._teamName;
		    }
		    set
		    {
		        this._teamName = value;
		    }
		}
		
		private bool _isEnabled;
		public virtual bool IsEnabled 
		{ 
		    get
		    {
		        return this._isEnabled;
		    }
		    set
		    {
		        this._isEnabled = value;
		    }
		}
		
	}
}
