#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;


namespace TeamThing.Model	
{
	public partial class ThingSource
	{
		private IList<ThingBase> _things;
		public virtual IList<ThingBase> Things 
		{ 
		    get
		    {
		        return this._things;
		    }
		    set
		    {
		        this._things = value;
		    }
		}
		
		private int _thingSourceId;
		public virtual int ThingSourceId 
		{ 
		    get
		    {
		        return this._thingSourceId;
		    }
		    set
		    {
		        this._thingSourceId = value;
		    }
		}
		
		private string _messageId;
		public virtual string MessageId 
		{ 
		    get
		    {
		        return this._messageId;
		    }
		    set
		    {
		        this._messageId = value;
		    }
		}
		
		private string _fromAddress;
		public virtual string FromAddress 
		{ 
		    get
		    {
		        return this._fromAddress;
		    }
		    set
		    {
		        this._fromAddress = value;
		    }
		}
		
		private DateTime _messageDate;
		public virtual DateTime MessageDate 
		{ 
		    get
		    {
		        return this._messageDate;
		    }
		    set
		    {
		        this._messageDate = value;
		    }
		}
		
		private string _messageBody;
		public virtual string MessageBody 
		{ 
		    get
		    {
		        return this._messageBody;
		    }
		    set
		    {
		        this._messageBody = value;
		    }
		}
		
		private DateTime _dateImported;
		public virtual DateTime DateImported 
		{ 
		    get
		    {
		        return this._dateImported;
		    }
		    set
		    {
		        this._dateImported = value;
		    }
		}
		
		private TeamMember _teamMember;
		public virtual TeamMember TeamMember 
		{ 
		    get
		    {
		        return this._teamMember;
		    }
		    set
		    {
		        this._teamMember = value;
		    }
		}
		
	}
}
